In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [5]:
#creates an array
#np.array(my_list)
np.array([1,2,3])

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#Return evenly spaced values within a given interval.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
#Return a new array of given shape and type, filled with zeros.
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#Return a new array of given shape and type, filled with ones.
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace
Return evenly spaced numbers over a specified interval.


In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

## eye
Creates an identity matrix

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.full((3,3), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

## Random
Numpy also has lots of ways to create random number arrays:

## rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [21]:
np.random.rand(5)

array([0.84845755, 0.48539038, 0.77281088, 0.50072903, 0.84001452])

## randint
Return random integers from low (inclusive) to high (exclusive).

In [22]:
np.random.randint(1,100,10)

array([15, 21, 71, 55, 75, 69, 39, 95, 40, 94])

## Reshape
Returns an array containing the same data with a new shape.

In [28]:
arr = np.arange(9)

In [29]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Indexing and Slicing

In [30]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
#Get a value at an index
arr[0]

0

In [32]:
arr[8]

8

In [34]:
arr[-2]

9

In [35]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [38]:
#Get values in a range
arr[0:5]
arr[:5]

array([0, 1, 2, 3, 4])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [46]:
#Taking Square Roots
arr = np.random.randint(1,100, 20) 
arr

array([74, 74, 61, 25, 20, 80, 32, 56, 61, 31, 77, 34, 84, 47, 34, 78, 25,
       14, 82, 46])

In [47]:
np.sqrt(arr)

array([8.60232527, 8.60232527, 7.81024968, 5.        , 4.47213595,
       8.94427191, 5.65685425, 7.48331477, 7.81024968, 5.56776436,
       8.77496439, 5.83095189, 9.16515139, 6.8556546 , 5.83095189,
       8.83176087, 5.        , 3.74165739, 9.05538514, 6.78232998])

In [48]:
np.max(arr)

84

In [49]:
# The sine of each element of x.
np.sin(arr)

array([-0.98514626, -0.98514626, -0.96611777, -0.13235175,  0.91294525,
       -0.99388865,  0.55142668, -0.521551  , -0.96611777, -0.40403765,
        0.99952016,  0.52908269,  0.73319032,  0.12357312,  0.52908269,
        0.51397846, -0.13235175,  0.99060736,  0.31322878,  0.90178835])

In [50]:
np.mean(arr)

51.75

In [51]:
np.median(arr)

51.5